### ISSUE TITLE
Kinect2_nidaq.exe wont open

### ISSUE THREAD

**Issue by Lynnkoehler** [dattalab/moseq2-app#263]
<When I try to open the Kinect2_nidaq.exe app it will not open>

## Expected Behavior
<I should get a new window as seen in the screen shot below.
<img width="858" alt="Screenshot 2024-01-29 at 10 20 35 AM" src="https://github.com/dattalab/moseq2-app/assets/157844052/bd684776-f75a-489b-a153-3c9efd210edc">

For context I have downloaded the necessary Kinect for Windows Runtime and Kinect for Windows SDK files
I have also downloaded the most recent NIDAQmx version. I used the most recent version because when I attempted to download version 17.6 I could not customize the settings to add 4.5.1 Language Support. >

## Current Behavior
<I have tried to open the folder using two different files with in the kinect2_nidaq_v0.2.3-alpha folder
when I try opening "C:\Users\roopr\OneDrive\Desktop\kinect2_nidaq_v0.2.3-alpha\kinect2_nidaq.application" I get the following pop up. >
![Screenshot 2024-01-29 100222](https://github.com/dattalab/moseq2-app/assets/157844052/0f1b3c4f-85b9-460d-9551-191a57fd1718).

When I tried to open the app "C:\Users\roopr\OneDrive\Desktop\kinect2_nidaq_v0.2.3-alpha\app.publish\kinect2_nidaq.exe" 
It simply would not open.

Note: I completed a clean windows 10 installation and the problem persists

## Context
With out this working I cannot connect the Kinect to my computer (my computer does not recognize the Kinect) and I cannot take videos.

## Your Environment
I am on a windows 11 computer with the same specs as those recommended in the computer building instructions

**Comment by versey-sherry** [comment]
Could you try downgrading your windows to windows 10 and try again?

**Comment by Lynnkoehler** [comment]
I will do this. I will have to uninstall windows 11 and reactivate windows 10.

**Comment by Lynnkoehler** [comment]
I completed a clean windows 10 installation and still ran into the same problem.

**Comment by versey-sherry** [comment]
Did you re-install all the drivers?

**Comment by Lynnkoehler** [comment]
yes i reinstalled all of the driviers (kinect runtime, kinect SDK, and ni-daqmx_24.0)

**Comment by gabrielpan147** [comment]
Hello, I met a quite similar situation these days. Did you solve this issue?
