### ISSUE TITLE
Quick question re: spray paint

### ISSUE THREAD

**Issue by ravikiran-raju** [dattalab/moseq2-app#264]
I apologize if I'm missing this information, but in the section on the "Moseq2 Bucket Preparation," I'm not seeing how the spray paint should be applied? Is the spray paint something that is still needed? And if so, any specifications on how it should be used would be great. Thanks so much!

**Comment by versey-sherry** [comment]
No, please don't paint the bucket

**Comment by ravikiran-raju** [comment]
Awesome! Thanks for the clarification and the quick reply! Cancelling the paint order...
