### ISSUE TITLE
Is it possible to use non-depth images?

### ISSUE THREAD

**Issue by danielpollak** [dattalab/moseq2-app#270]
I have a dataset of videos taken with a machine vision camera. Alas, these videos do not have depth information. Would it be possible to run my data through moseq2 by binarizing them, making them effectively depth videos with a single height?

## Is your feature request related to a problem? Please describe.

The only problem is I have already collected my data.

## Expected Behavior

I would like to be able to get behavioral motifs, if not of equal quality to the kind you'd get with kinect videos, then at least of comparable quality.

## Current Behavior

I do not have the moseq2 pipeline running at all yet.

## Possible Solution

Could one hack moseq2 by providing binarized videos of mouse behavior, thus emulating the expected datatype expected by the software?

## Alternatives Considered

I could get a kinect camera, but I don't know how to synchronize it with neuropixel data, nor if that's possible.

**Comment by versey-sherry** [comment]
Please check out https://keypoint-moseq.readthedocs.io/en/latest/
